### ISSUE TITLE
Pre-flight checklist

### ISSUE THREAD

**Issue by loklaan** [woadtoad/love-boilerplate#1]
- [x] make it easy to have one off effects made with texmate. which destroy themselves after playing.
- [x] have way of looping tweens be easier
- [x] improve texmatestatic,flag to ignore trim data,flag to change alignment, (edited)
- [ ] make sti and jumper example, perhaps combined with hardon
- [ ] make simple default menu system (edited)
- [ ] make a simple splashscreen scene where we can just substitute an image
- [x] fix repeat frame bug on texmate when animating with a callback
- [ ] texmate, pass through colour
- [ ] flag to stop looping of anim
- [x] stop flipping by default
- [x] put in error messages for when she breaks with texmate so things are easier to understand.
- [x] implement hot loading with lurker https://github.com/rxi/lurker
- [x] add debugging cli args from dryrun
- [x] abstract scene management

**Comment by loklaan** [comment]
Hey @Muzz I don't have the familiarity with this any longer to push for a standalone boilerplate. Should we leave this issue to die?

**Comment by Muzz** [comment]
@loklaan Slacker, why did you get to this 10 years later. Dissapointed.
